
# capabilities.py
"""Capability map for each upstream pipeline type."""
from __future__ import annotations
from typing import Dict, Set

FEATURES: Set[str] = {
    "DEGS","PATHWAYS","TF_REGULATORS","EPI_REGULATORS","METABOLITES",
    "VIPER_TF","ULM_PANELS","BASELINE_DELTA","OVERLAP_JSONS",
}

CAPABILITY_MAP: Dict[str, Set[str]] = {
    "COUNTS": {"DEGS","PATHWAYS","TF_REGULATORS","EPI_REGULATORS","METABOLITES","VIPER_TF","ULM_PANELS","BASELINE_DELTA","OVERLAP_JSONS"},
    "DEGS":   {"DEGS","PATHWAYS","TF_REGULATORS","EPI_REGULATORS","METABOLITES","ULM_PANELS","OVERLAP_JSONS"},
    "GL":     {"PATHWAYS","TF_REGULATORS","EPI_REGULATORS","METABOLITES","OVERLAP_JSONS"},
    "GC":     {"PATHWAYS","TF_REGULATORS","EPI_REGULATORS","METABOLITES","OVERLAP_JSONS"},
    "JSONS":  {"OVERLAP_JSONS"},
}
