"""
cli.py — entry point for the molecular causal discovery pipeline.

Usage:
    python cli.py "your query" [file1 file2 ...]

Two modes:
    Interactive (default):    agent asks clarifying questions before running.
    Non-interactive (--no-interact): skip questions and run immediately.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from agent import SupervisorAgent


def save_result(result_dict: dict, output_dir: str = ".") -> str:
    """
    Persist the full pipeline result dict to a JSON file.

    Args:
        result_dict: The dict returned by SupervisorAgent.run().
        output_dir:  Directory to write the file into (created if missing).

    Returns:
        Absolute path of the written file.
    """
    out_dir  = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    run_id   = result_dict.get("run_id", "run_unknown")
    out_path = out_dir / f"{run_id}_result.json"
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(result_dict, fh, indent=2, ensure_ascii=False, default=str)
    return str(out_path)


def _run_clarification(agent: SupervisorAgent, query: str, files: list) -> object:
    """
    Ask the user the clarifying questions generated by the agent.

    Returns a ClarificationResult (or None if interaction was skipped / no questions).
    """
    questions = agent.pre_clarify(query, files)

    if not questions:
        return None

    sep = "-" * 60
    print(f"\n{sep}")
    print("  CLARIFICATION  -- please answer before the pipeline runs")
    print("  (Press Enter to skip any question)")
    print(sep)

    answers: list[str] = []
    for q in questions:
        print(f"\n  {q}")
        try:
            ans = input("  Your answer: ").strip()
        except (EOFError, KeyboardInterrupt):
            ans = ""
        answers.append(ans)

    print(f"\n{sep}")
    print("  Summary of your answers:")
    any_answered = False
    for q, a in zip(questions, answers):
        if a:
            q_short = q.lstrip("1234567890. ").split("?")[0] + "?"
            print(f"    {q_short[:55]:55s}  ->  {a[:40]}")
            any_answered = True
    if not any_answered:
        print("    (all questions skipped)")
    print(sep)

    try:
        confirm = input("\n  Proceed with these answers? [Y/n]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        confirm = "y"

    if confirm in ("n", "no"):
        print("  Re-run to answer again.")
        sys.exit(0)

    return agent.build_clarification(query, questions, answers, skipped=not any_answered)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Molecular Causal Discovery Platform",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive (default) -- agent asks clarifying questions first
  python cli.py "Find causal drivers of colorectal cancer"

  # With data files -- agent skips questions it can answer from the files
  python cli.py "Find causal drivers of colorectal cancer" counts.csv metadata.csv

  # Skip interaction entirely
  python cli.py "Find causal drivers of colorectal cancer" --no-interact

  # Directed causality with two files
  python cli.py "Does TP53 causally drive EMT in breast cancer?" expression.csv metadata.csv

  # Counterfactual simulation
  python cli.py "Simulate inhibiting KRAS by 80% in PDAC"

  # Compare groups
  python cli.py "Compare causal drivers between responders and non-responders" \\
      expr.csv metadata_with_response.csv temporal_fits.tsv

  # Skip literature search for faster offline run
  python cli.py "Find causal drivers of IBD" counts.tsv meta.csv --skip-lit
        """,
    )
    parser.add_argument("query",            help="Natural language causal question")
    parser.add_argument("files", nargs="*", help="Data file paths (CSV/TSV/h5ad/xlsx)")
    parser.add_argument("--no-interact",    action="store_true",
                        help="Skip clarification questions and run immediately")
    parser.add_argument("--skip-lit",       action="store_true",
                        help="Skip literature pipeline (faster, no HTTP calls)")
    parser.add_argument("--output-dir",     default="./results",
                        help="Directory to save result JSON (default: ./results)")
    parser.add_argument("--api-key",        default=None,
                        help="Anthropic API key (or set ANTHROPIC_API_KEY env var)")
    parser.add_argument("--quiet",          action="store_true",
                        help="Suppress progress output (implies --no-interact)")

    args = parser.parse_args()

    try:
        agent = SupervisorAgent(api_key=args.api_key)

        # Clarification step
        clarification_result = None
        if not args.no_interact and not args.quiet:
            clarification_result = _run_clarification(agent, args.query, args.files)

        # Run pipeline
        result = agent.run(
            query                = args.query,
            file_paths           = args.files,
            clarification_result = clarification_result,
            skip_literature      = args.skip_lit,
            verbose              = not args.quiet,
            output_dir           = args.output_dir,
        )

        if result.get("status") == "needs_clarification":
            print(f"\nAdditional clarification needed:\n   {result['clarifying_question']}")
            print("\nRe-run and answer the clarification question when prompted.")
            sys.exit(2)

        saved = save_result(result, args.output_dir)
        if not args.quiet:
            print(f"\nResult saved to: {saved}")

        sys.exit(0 if result.get("status") == "complete" else 1)

    except RuntimeError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(130)


if __name__ == "__main__":
    main()
