import os
import pandas as pd
from agents import function_tool

@function_tool
def combine_deg_outputs(results_root_dir: str, output_file: str = "combined_DEGs_matrix_annotated.csv") -> str:
    """
    📊 Combines all DEG result files into a single annotated matrix.

    This tool scans the given results directory (e.g. 'data/liver_cancer') and finds all *_DEGs.csv files
    generated by the self-coding DEG agent. For each file, it extracts columns: 'log2FoldChange', 'pvalue', and 'padj',
    and merges them into one matrix using gene IDs. The column names are prefixed by the dataset name (e.g., GSE176496_log2FC).

    Parameters:
    - results_root_dir (str): Path to the disease results directory containing GSE subfolders.
    - output_file (str): Final combined output file name (default: 'combined_DEGs_matrix_annotated.csv').

    Returns:
    - str: Path to the saved combined CSV file, or a warning message if no DEG files found.
    """

    combined_df = None
    deg_files = []

    for root, dirs, files in os.walk(results_root_dir):
        for file in files:
            if file.endswith("_DEGs.csv"):
                deg_files.append(os.path.join(root, file))

    if not deg_files:
        return f"❌ No DEG result files found in {results_root_dir}. Please check if the DEG agent ran successfully."

    for file_path in deg_files:
        dataset_id = os.path.basename(file_path).split("_DEGs.csv")[0]
        df = pd.read_csv(file_path)

        # Auto-detect gene ID column
        gene_col = next((col for col in ['Gene', 'gene', 'GeneID', 'Ensembl_id'] if col in df.columns), None)
        if not gene_col:
            continue  # Skip if gene column is missing

        df = df[[gene_col, 'log2FoldChange', 'pvalue', 'padj']].copy()
        df = df.rename(columns={
            'log2FoldChange': f'{dataset_id}_log2FC',
            'pvalue': f'{dataset_id}_pval',
            'padj': f'{dataset_id}_padj'
        })

        if combined_df is None:
            combined_df = df
        else:
            combined_df = pd.merge(combined_df, df, on=gene_col, how='outer')

    output_path = os.path.join(results_root_dir, output_file)
    combined_df.to_csv(output_path, index=False)

    return f"✅ Combined DEG matrix saved to: {output_path}"
